spring:
  application:
    name: security

  # Database Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/security_guard
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:Admin@123}
    driverClassName: org.postgresql.Driver

  # Email Configuration for Password Recovery
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Flyway config
  flyway:
    default-schema: public
    create-schemas: true
    clean-disabled: false

# JWT Configuration
security:
  jwt:
    secret-key: ${SECRET_KEY:m+nAq8hF2FqZbQAo5sdWzQ7YtFD9Yymxeo6l8ujKkJKcV5gTgJ+yvD0TC0ajUq5xUpD9OyQb6G7pWW7zKwxdFg==}
    expiration: 86400000       # 24 horas
    refresh-token:
      expiration: 604800000    # 7 dias

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan:  br.com.soejin.framework.security_guard.controller

